FROM node:16.13.1-alpine3.13

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add app
COPY . ./

#EXPOSE 3001

# NODE_ENV=production kertoo sequelizelle, että postgres osoite on docker kontin nimi, eikä localhost
# löytyy sequelizen conffitiedostosta: /backend/config/config.js
ENV NODE_ENV production

CMD ["node", "server.js"]
